// 课程 + 刷题 + 错题/收藏/学习记录逻辑
let state={cat:null,subj:null,idx:[],questions:[],idxPos:0,answers:{},quizMode:'paper',quizLabel:'',courseOpen:true,lessonId:null};
function store(k,v){if(v===undefined){try{return JSON.parse(localStorage.getItem('gktk_'+k))||{}}catch(e){return{}}}localStorage.setItem('gktk_'+k,JSON.stringify(v))}
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(page).classList.add('active');if(page==='home')renderHome();if(page==='picker')renderPicker();window.scrollTo(0,0)}
function renderHome(){const prog=store('progress'),total=Object.values(prog).reduce((a,p)=>a+(p.done||0),0),right=Object.values(prog).reduce((a,p)=>a+(p.right||0),0);document.getElementById('globalStats').textContent=total?`累计刷题 ${total} 道，答对 ${right} 道，正确率 ${Math.round(right/total*100)}%`:'开始你的第一次刷题吧！';renderContinueLearning();document.getElementById('mistakeCount').textContent=Object.keys(store('mistakes')).length;document.getElementById('favoriteCount').textContent=Object.keys(store('favorites')).length;const grid=document.getElementById('categoryGrid');grid.innerHTML='';CATS.forEach(c=>{const p=prog[c.id]||{},d=document.createElement('div');d.className='cat-card';d.innerHTML=`<h3>${c.name}</h3><p>${c.desc}</p>${p.done?`<p class="done">已刷 ${p.done} 道 · 正确率 ${Math.round((p.right||0)/p.done*100)}%</p>`:''}`;d.onclick=()=>{state.cat=c.id;state.subj=null;go('picker')};grid.appendChild(d)})}
async function renderPicker(){const cat=CATS.find(c=>c.id===state.cat);document.getElementById('pickerTitle').textContent=cat.name+' · 课程与题库';document.getElementById('pickerIntro').textContent=COURSE_CATALOG[state.cat].intro;const tabs=document.getElementById('subjTabs');tabs.innerHTML='';Object.keys(cat.subjects).forEach(s=>{const b=document.createElement('button');b.className='subj-tab'+(state.subj===s?' on':'');b.textContent=cat.subjects[s];b.onclick=()=>{state.subj=s;renderPicker()};tabs.appendChild(b)});if(!state.subj||!cat.subjects[state.subj])state.subj=Object.keys(cat.subjects)[0];document.getElementById('randomBtn').style.display=state.subj==='shenlun'||state.subj==='zongying'?'none':'inline-block';renderLessonCenter();renderCourse();document.getElementById('yearList').innerHTML='<p class="loading">加载中…</p>';const r=await loadIndex(state.cat,state.subj);state.idx=r.index;document.getElementById('paperCount').textContent=`${state.idx.length} 套卷`;renderYearList()}
function renderCourse(){const list=document.getElementById('courseList');list.innerHTML='';if(!state.courseOpen){list.style.display='none';return}list.style.display='grid';courseFor(state.cat,state.subj).forEach((c,i)=>{const topic=Array.isArray(c)?c[0]:c.title,desc=Array.isArray(c)?c[1]:c.summary;const d=document.createElement('div');d.className='course-item';d.innerHTML=`<span class="lesson-num">${i+1}</span><div><b>${esc(topic)}</b><small>${esc(desc)}</small></div><span class="lesson-go">练习 →</span>`;d.onclick=()=>startPractice(topic);list.appendChild(d)})}
function toggleCourse(){state.courseOpen=!state.courseOpen;renderCourse()}
function renderYearList(){const box=document.getElementById('yearList'),kw=(document.getElementById('searchInput').value||'').trim(),entries=state.idx.filter(e=>!kw||e.key.includes(kw));box.innerHTML='';if(!entries.length){box.innerHTML='<p class="loading">没有匹配的试卷</p>';return}entries.forEach(e=>{const d=document.createElement('div');d.className='year-block';const [y,...rest]=e.key.split('·');d.innerHTML=`<h3>${y} 年 ${esc(rest.join(' '))}</h3><button class="start-btn">开始刷题（${e.count} 题）</button>`;d.querySelector('button').onclick=()=>startQuiz(e.key);box.appendChild(d)})}
function yearOf(k){return/^\d{4}/.test(k)?k.slice(0,4):'other'}
async function startQuiz(key){const papers=await loadYearPapers(state.cat,state.subj,yearOf(key)),list=papers[key]||[];if(!list.length){alert('该卷数据加载失败，请重试');return}state.questions=list.slice();state.quizLabel=key;state.quizMode='paper';beginQuiz()}
async function startRandom(){const pool=state.idx.filter(e=>e.count>=20);if(!pool.length){alert('暂无题目');return}const pick=pool[Math.floor(Math.random()*pool.length)],papers=await loadYearPapers(state.cat,state.subj,yearOf(pick.key)),list=(papers[pick.key]||[]).slice();shuffle(list);state.questions=list.slice(0,20);state.quizLabel='随机抽题 · '+pick.key;state.quizMode='random';beginQuiz()}
function startPractice(topic){startPracticeAsync(topic)}
async function startPracticeAsync(topic){const items=[];const practice=await loadPractice(state.cat,state.subj);for(const q of practice)if(!topic||q.module===topic)items.push(q);if(items.length<5){for(const e of state.idx.filter(e=>e.count>0).slice(0,20)){const p=await loadYearPapers(state.cat,state.subj,yearOf(e.key));for(const q of(p[e.key]||[]))if(!topic||(q.t||q.type||'').includes(topic))items.push(q)}}if(!items.length){alert('该模块暂无练习题');return}shuffle(items);state.questions=items.slice(0,20);state.quizLabel='专项练习 · '+topic;state.quizMode='practice';beginQuiz()}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}}
function beginQuiz(){state.idxPos=0;state.answers={};go('quiz');renderQuestion()}
function questionId(q){if(q.id||q.fenbi_id)return q.id||q.fenbi_id;return[state.cat||'unknown',state.subj||'unknown',state.quizLabel||'unknown',hash(q.stem||q.q||''),hash(JSON.stringify(q.options||q.o||[]))].join(':')}
function normQ(q){return{type:q.type||q.t||'',material:q.material||q.s||'',stem:q.stem||q.q||'',options:q.options||q.o||null,answer:q.answer||q.a||'',analysis:q.analysis||q.e||'',id:questionId(q)}}
function hash(s){let h=0;for(let i=0;i<s.length;i++)h=((h<<5)-h+s.charCodeAt(i))|0;return String(h)}
function renderQuestion(){const raw=state.questions[state.idxPos];if(!raw)return;const q=normQ(raw),n=state.questions.length,id=q.id;document.getElementById('quizMeta').textContent=`${CATS.find(c=>c.id===state.cat).name} · ${CATS.find(c=>c.id===state.cat).subjects[state.subj]} · ${state.quizLabel} · 第 ${state.idxPos+1}/${n} 题`;document.getElementById('progressFill').style.width=((state.idxPos+1)/n*100)+'%';const fav=store('favorites');document.getElementById('favoriteBtn').textContent=fav[id]?'★ 已收藏':'☆ 收藏';let html='';if(q.material)html+=`<div class="material">${esc(q.material)}</div>`;if(q.type)html+=`<span class="q-type">${esc(q.type)}</span>`;html+=`<div class="q-stem">${state.idxPos+1}. ${esc(q.stem)}</div>`;if(q.options&&q.options.length){const chosen=state.answers[state.idxPos],letters='ABCDEFGH';q.options.forEach((o,i)=>{const l=letters[i];let cls='opt';if(chosen!==undefined){cls+=' disabled';if(q.answer.includes(l))cls+=' correct';else if(l===chosen)cls+=' wrong'}html+=`<button class="${cls}" onclick="answer('${l}')">${l}. ${esc(o)}</button>`})}else html+='<p class="subjective-tip">主观题：请先在脑中或纸上作答，再展开参考答案。</p>';document.getElementById('questionBox').innerHTML=html;document.getElementById('analysisBox').classList.add('hidden');document.getElementById('prevBtn').disabled=state.idxPos===0;document.getElementById('nextBtn').textContent=state.idxPos===n-1?'完成':'下一题'}
function answer(letter){if(state.answers[state.idxPos]!==undefined)return;state.answers[state.idxPos]=letter;const q=normQ(state.questions[state.idxPos]),id=q.id,prog=store('progress'),p=prog[state.cat]=prog[state.cat]||{done:0,right:0};p.done++;if(q.answer.includes(letter))p.right++;store('progress',prog);const hist=store('history');hist[Date.now()]={cat:state.cat,subj:state.subj,label:state.quizLabel,qid:id,right:q.answer.includes(letter)};store('history',hist);if(!q.answer.includes(letter)){const mis=store('mistakes');mis[id]={...q,cat:state.cat,subj:state.subj};store('mistakes',mis)}renderQuestion();toggleAnalysis(true)}
function toggleFavorite(){const q=normQ(state.questions[state.idxPos]),f=store('favorites');if(f[q.id])delete f[q.id];else f[q.id]={...q,cat:state.cat,subj:state.subj};store('favorites',f);renderQuestion()}
function toggleAnalysis(force){const b=document.getElementById('analysisBox'),q=normQ(state.questions[state.idxPos]||{});if(force===true||b.classList.contains('hidden')){b.textContent=(q.answer&&q.options?`【答案】${q.answer}\n`:'')+'【解析】'+(q.analysis||'暂无解析');b.classList.remove('hidden')}else b.classList.add('hidden')}
function nav(d){if(d===1&&state.idxPos===state.questions.length-1)return showResult();state.idxPos=Math.max(0,Math.min(state.questions.length-1,state.idxPos+d));renderQuestion()}
function showResult(){let r=0,a=0,o=0;state.questions.forEach((raw,i)=>{const q=normQ(raw);if(q.options){o++;if(state.answers[i]!==undefined){a++;if(q.answer.includes(state.answers[i]))r++}}});document.getElementById('resultBox').innerHTML=o?`<div class="score">${r} / ${o}</div><p>已作答 ${a} 题 · 正确率 ${a?Math.round(r/a*100):0}%</p>`:`<div class="score">✍️</div><p>主观题练习完成，共 ${state.questions.length} 题。</p>`;go('result')}
function openLearning(type){const titles={mistakes:'错题本',favorites:'收藏题',history:'学习记录'};document.getElementById('learningTitle').textContent=titles[type];const box=document.getElementById('learningList'),data=store(type);box.innerHTML='';const vals=Object.values(data).reverse();if(!vals.length){box.innerHTML='<p class="loading">这里还没有记录</p>';go('learning');return}vals.slice(0,100).forEach((q,i)=>{const d=document.createElement('div');d.className='learning-item';d.innerHTML=`<b>${i+1}. ${esc(q.stem||q.q||q.label||'学习记录')}</b><small>${esc(q.type||q.t||q.label||'')}</small>`;if(q.stem||q.q)d.onclick=()=>{state.cat=q.cat;state.subj=q.subj;state.questions=[q];state.quizLabel='错题/收藏复习';beginQuiz()};box.appendChild(d)});go('learning')}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}function escAttr(s){return esc(s).replace(/"/g,'&quot;')}
renderHome();
